### ISSUE TITLE
Does not work. 

### ISSUE THREAD

**Issue by scottprovost** [brenns10/cbot#30]
./sample.cfg:10: syntax error (cbot config op read)lab@lab:~/git/cbot$

**Comment by brenns10** [comment]
Hi @scottprovost looks like the "syntax error" in the sample config is that there is a trailing comma on line 9:
https://github.com/brenns10/cbot/blob/master/sample.cfg#L9

It's likely that your libconfig library version is less than 1.7: https://github.com/hyperrealm/libconfig/blob/master/ChangeLog#L34

Mine is above 1.7 so I hadn't gotten these errors.

The simplest thing is to remove the trailing comma on line 9. I thought I had caught them all but clearly not. I'll remove it from the sample.cfg, but you'll want to make sure to watch out for the trailing commas as you modify and create your own configuration file. Personally I find libconfig <1.7 to be extraordinarily painful due to this trailing comma limitation :(

**Comment by brenns10** [comment]
Also if you have any feedback on cbot let me know :)
You may be the first person who isn't me to run it.
